#!/usr/bin/env bash
#install bginx on web server, listening on Port 80

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.html
service nginx start
