#!/usr/bin/env bash
#prints 1-20,luck indictaors on 4,9,17

num=1

while [ $num -le 20 ]; do
	case $num in
[1-3]|[5-8]|1[0-6]|1[8-9])
	echo $num
;;

4)
	echo $num
	echo bad luck from China
;;

9)
	echo $num
	echo bad luck from Japan
;;
17)
	echo $num
	echo bad luck from Italy
;;
20)
	echo $num
;;
esac
	num=$((num + 1))
done

