#!/usr/bin/env bash
#Checks if file exists
#checks if file is empty
#check if its a normal file

#checks if file exists
if [ -e "school" ]; then
	echo school file exists
if [ -s "school" ]; then
	echo school file is not empty
else
	echo school file is empty
fi
if [ -f "school" ]; then
	echo school is a regular file
fi
	
else
	echo school file does not exist
fi
